
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Apr 27 19:46:26 UTC 2023
//----------------------------------------------------

package me.josecomparotto.compilador.syntax;

/** CUP generated class containing symbol constants. */
public class JCupSymbols {
  /* terminals */
  public static final int KEYWORD_SOREIGAI = 5;
  public static final int KEYWORD_HO = 9;
  public static final int LESS_THEN_OR_EQUALS_OPERATOR = 24;
  public static final int ADD_OPERATOR = 20;
  public static final int PRODUCT_OPERATOR = 18;
  public static final int NUMBER_LITERAL = 33;
  public static final int SEMICOLON = 2;
  public static final int KEYWORD_NISE = 10;
  public static final int PARENTHESIS_OPENING = 29;
  public static final int KEYWORD_KARA = 7;
  public static final int KEYWORD_MOSHI = 4;
  public static final int INPUT_LINE_KEY = 16;
  public static final int KEYWORD_MO = 13;
  public static final int KEYWORD_KAKU = 3;
  public static final int EOF = 0;
  public static final int CONCAT_OPERATOR = 17;
  public static final int GREATER_THEN_OPERATOR = 26;
  public static final int error = 1;
  public static final int BLOCK_CLOSURE = 32;
  public static final int KEYWORD_MATA = 14;
  public static final int TEXT_LITERAL = 34;
  public static final int INPUT_VALUE_KEY = 15;
  public static final int EQUALS_OPERATOR = 23;
  public static final int KEYWORD_SHIN = 11;
  public static final int GREATER_THEN_OR_EQUALS_OPERATOR = 25;
  public static final int DIV_OPERATOR = 19;
  public static final int KEYWORD_MADE = 8;
  public static final int ASSIGNMENT_OPERATOR = 28;
  public static final int NOT_EQUALS_OPERATOR = 22;
  public static final int LESS_THEN_OPERATOR = 27;
  public static final int KEYWORD_TAMENI = 6;
  public static final int SUB_OPERATOR = 21;
  public static final int PARENTHESIS_CLOSURE = 30;
  public static final int BLOCK_OPENING = 31;
  public static final int KEYWORD_SHINAI = 12;
  public static final int IDENTIFIER = 35;
}

