
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Sun May 21 17:59:35 UTC 2023
//----------------------------------------------------

package me.josecomparotto.compilador.syntax;

/** CUP generated class containing symbol constants. */
public class JCupSymbols {
  /* terminals */
  public static final int KEYWORD_SOREIGAI = 5;
  public static final int KEYWORD_HO = 9;
  public static final int ASTERISK = 18;
  public static final int SLASH = 19;
  public static final int PERIOD = 17;
  public static final int NUMBER_LITERAL = 33;
  public static final int DOUBLE_EQUALS = 23;
  public static final int DOUBLE_QUESTION_MARK = 16;
  public static final int SEMICOLON = 2;
  public static final int KEYWORD_NISE = 10;
  public static final int KEYWORD_KARA = 7;
  public static final int QUESTION_MARK = 15;
  public static final int KEYWORD_MOSHI = 4;
  public static final int PLUS = 20;
  public static final int KEYWORD_MO = 13;
  public static final int KEYWORD_KAKU = 3;
  public static final int EOF = 0;
  public static final int COLON_EQUALS = 28;
  public static final int error = 1;
  public static final int KEYWORD_MATA = 14;
  public static final int OPEN_BRACE = 31;
  public static final int TEXT_LITERAL = 34;
  public static final int GREATER_THEN_EQUALS = 25;
  public static final int LESS_THEN = 27;
  public static final int LESS_THEN_EQUALS = 24;
  public static final int OPEN_PARENTHESIS = 29;
  public static final int KEYWORD_SHIN = 11;
  public static final int KEYWORD_MADE = 8;
  public static final int EXCLAMATION_EQUALS = 22;
  public static final int KEYWORD_TAMENI = 6;
  public static final int CLOSE_PARENTHESIS = 30;
  public static final int CLOSE_BRACE = 32;
  public static final int HYPHEN = 21;
  public static final int GREATER_THEN = 26;
  public static final int KEYWORD_SHINAI = 12;
  public static final int IDENTIFIER = 35;
}

