
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Sat Apr 15 14:54:41 UTC 2023
//----------------------------------------------------

package me.josecomparotto.cbr.syntax;

/** CUP generated class containing symbol constants. */
public class JCupSymbols {
  /* terminals */
  public static final int SUB_OPERATOR = 20;
  public static final int SUM_OPERATOR = 19;
  public static final int SEMICOLON = 2;
  public static final int KEYWORD_NISE = 12;
  public static final int PARENTHESIS_CLOSURE = 29;
  public static final int BLOCK_CLOSURE = 31;
  public static final int KEYWORD_KAKU = 4;
  public static final int NOT_EQUALS_OPERATOR = 21;
  public static final int KEYWORD_TAMENI = 8;
  public static final int IDENTIFIER = 34;
  public static final int PRODUCT_OPERATOR = 17;
  public static final int GREATER_THEN_OR_EQUALS_OPERATOR = 24;
  public static final int KEYWORD_SHINAI = 14;
  public static final int LESS_THEN_OR_EQUALS_OPERATOR = 23;
  public static final int PARENTHESIS_OPENING = 28;
  public static final int KEYWORD_MADE = 10;
  public static final int BLOCK_OPENING = 30;
  public static final int KEYWORD_MOSHI = 6;
  public static final int DIV_OPERATOR = 18;
  public static final int COMMA = 3;
  public static final int KEYWORD_MO = 15;
  public static final int EOF = 0;
  public static final int LESS_THEN_OPERATOR = 26;
  public static final int NUMBER_LITERAL = 32;
  public static final int EQUALS_OPERATOR = 22;
  public static final int ASSIGNMENT_OPERATOR = 27;
  public static final int KEYWORD_YOMU = 5;
  public static final int KEYWORD_SHIN = 13;
  public static final int error = 1;
  public static final int KEYWORD_SOREIGAI = 7;
  public static final int TEXT_LITERAL = 33;
  public static final int KEYWORD_HO = 11;
  public static final int GREATER_THEN_OPERATOR = 25;
  public static final int KEYWORD_MATA = 16;
  public static final int KEYWORD_KARA = 9;
}

